language: node_js
node_js:
  - 12
services:
  - docker
install: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_eb6eb26fba1d_key -iv $encrypted_eb6eb26fba1d_iv
    -in travis_deploy_rsa.enc -out travis_deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_deploy_rsa
  - ssh-add travis_deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./build.sh
  on:
    branch: master
