packageExtensions:
  "@types/eslint-plugin-prettier@*":
    dependencies:
      eslint: "^7.6.0"
  next@*:
    dependencies:
      "@types/react": "^16.9.46"
      "@types/webpack": "^4"
      "caniuse-lite": "^1.0.30001114"
  "@types/cors@*":
    dependencies:
      express: "^4.17.1"
  "@types/express@*":
    dependencies:
      "body-parser": "^1.19.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
