packageExtensions:
  "@material-ui/types@*":
    dependencies:
      react: 16.13.1
  "@types/cors@*":
    dependencies:
      express: ^4.17.1
  "@types/eslint-plugin-prettier@*":
    dependencies:
      eslint: ^7.6.0
  "@types/express@*":
    dependencies:
      body-parser: ^1.19.0
  "@types/multer@*":
    dependencies:
      express: ^4.17.1
  "@types/react-transition-group@*":
    dependencies:
      react: 16.13.1
  next@*:
    dependencies:
      "@types/react": ^16.9.46
      "@types/webpack": ^4
      caniuse-lite: ^1.0.30001114
  typeorm@*:
    dependencies:
      mysql: ^2.18.1
      pg: ^8.3.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
