version: "3.7"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    links:
      - postgres
      - minio
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./server:/app/server
      - ./types:/app/types

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./.minio-data:/data
    command: server /data
